//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slot {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slot.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка на API!.
        /// </summary>
        internal static string APIError {
            get {
                return ResourceManager.GetString("APIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атрибуты.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступный объем.
        /// </summary>
        internal static string AvailableFree {
            get {
                return ResourceManager.GetString("AvailableFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логическое.
        /// </summary>
        internal static string Bool {
            get {
                return ResourceManager.GetString("Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brotli.
        /// </summary>
        internal static string Brotli {
            get {
                return ResourceManager.GetString("Brotli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Байт.
        /// </summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Символ.
        /// </summary>
        internal static string Char {
            get {
                return ResourceManager.GetString("Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В БУФЕР ОБМЕНА.
        /// </summary>
        internal static string ClipboardButton {
            get {
                return ResourceManager.GetString("ClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комрессия.
        /// </summary>
        internal static string Compress {
            get {
                return ResourceManager.GetString("Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать файл.
        /// </summary>
        internal static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя поддиректории.
        /// </summary>
        internal static string CreateSubdir {
            get {
                return ResourceManager.GetString("CreateSubdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время создания.
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декомпрессия.
        /// </summary>
        internal static string Decompress {
            get {
                return ResourceManager.GetString("Decompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deflate.
        /// </summary>
        internal static string Deflate {
            get {
                return ResourceManager.GetString("Deflate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будущий путь.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите путь до файла:.
        /// </summary>
        internal static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла с расширением.
        /// </summary>
        internal static string DestinationPathExample {
            get {
                return ResourceManager.GetString("DestinationPathExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на убить.
        /// </summary>
        internal static string Destructive {
            get {
                return ResourceManager.GetString("Destructive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталоги.
        /// </summary>
        internal static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя директории.
        /// </summary>
        internal static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные файла....
        /// </summary>
        internal static string DocumentPlaceholder {
            get {
                return ResourceManager.GetString("DocumentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Десятичное.
        /// </summary>
        internal static string Double {
            get {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о диске.
        /// </summary>
        internal static string DriveInfoMessage {
            get {
                return ResourceManager.GetString("DriveInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обозреватель.
        /// </summary>
        internal static string DriveInfoTitle {
            get {
                return ResourceManager.GetString("DriveInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя диска.
        /// </summary>
        internal static string DriveName {
            get {
                return ResourceManager.GetString("DriveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите абсолютный путь.
        /// </summary>
        internal static string EnterAbsolutePath {
            get {
                return ResourceManager.GetString("EnterAbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите тип значения:.
        /// </summary>
        internal static string EnterBinaryType {
            get {
                return ResourceManager.GetString("EnterBinaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите значение.
        /// </summary>
        internal static string EnterBinValue {
            get {
                return ResourceManager.GetString("EnterBinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь относительно пакета.
        /// </summary>
        internal static string EnterDestinationPath {
            get {
                return ResourceManager.GetString("EnterDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите JSON Коммент.
        /// </summary>
        internal static string EnterJsonComment {
            get {
                return ResourceManager.GetString("EnterJsonComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите JSON свойство.
        /// </summary>
        internal static string EnterJsonProperty {
            get {
                return ResourceManager.GetString("EnterJsonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите JSON тип.
        /// </summary>
        internal static string EnterJsonType {
            get {
                return ResourceManager.GetString("EnterJsonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите JSON значение.
        /// </summary>
        internal static string EnterJsonValue {
            get {
                return ResourceManager.GetString("EnterJsonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст....
        /// </summary>
        internal static string EnterTextValue {
            get {
                return ResourceManager.GetString("EnterTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание XML атрибута.
        /// </summary>
        internal static string EnterXmlAttribute {
            get {
                return ResourceManager.GetString("EnterXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите комментарий XML.
        /// </summary>
        internal static string EnterXmlComment {
            get {
                return ResourceManager.GetString("EnterXmlComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание XML элемента.
        /// </summary>
        internal static string EnterXmlElement {
            get {
                return ResourceManager.GetString("EnterXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя тега.
        /// </summary>
        internal static string EnterXmlName {
            get {
                return ResourceManager.GetString("EnterXmlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите XML значение.
        /// </summary>
        internal static string EnterXmlValue {
            get {
                return ResourceManager.GetString("EnterXmlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проводник.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите экспортный URI .
        /// </summary>
        internal static string ExportUri {
            get {
                return ResourceManager.GetString("ExportUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширение.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бинарный файл.
        /// </summary>
        internal static string FileBinPageTitle {
            get {
                return ResourceManager.GetString("FileBinPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сведения.
        /// </summary>
        internal static string FileInfoTitle {
            get {
                return ResourceManager.GetString("FileInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное имя.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GZip.
        /// </summary>
        internal static string GZip {
            get {
                return ResourceManager.GetString("GZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        internal static string ImagePageTitle {
            get {
                return ResourceManager.GetString("ImagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите импортный URI.
        /// </summary>
        internal static string ImportUri {
            get {
                return ResourceManager.GetString("ImportUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Целочисленный.
        /// </summary>
        internal static string Int {
            get {
                return ResourceManager.GetString("Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невалидный JSON файл.
        /// </summary>
        internal static string InvalidJsonFile {
            get {
                return ResourceManager.GetString("InvalidJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невалидный XML файл!.
        /// </summary>
        internal static string InvalidXmlFile {
            get {
                return ResourceManager.GetString("InvalidXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла IO ошибка!.
        /// </summary>
        internal static string IOError {
            get {
                return ResourceManager.GetString("IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IO операция.
        /// </summary>
        internal static string IOMessage {
            get {
                return ResourceManager.GetString("IOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов к IO.
        /// </summary>
        internal static string IsReady {
            get {
                return ResourceManager.GetString("IsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВОЙТИ.
        /// </summary>
        internal static string IsSignIn {
            get {
                return ResourceManager.GetString("IsSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВСТУПИТЬ.
        /// </summary>
        internal static string IsSignUp {
            get {
                return ResourceManager.GetString("IsSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //.
        /// </summary>
        internal static string JsonComment {
            get {
                return ResourceManager.GetString("JsonComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ].
        /// </summary>
        internal static string JsonEndArray {
            get {
                return ResourceManager.GetString("JsonEndArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на }.
        /// </summary>
        internal static string JsonEndObject {
            get {
                return ResourceManager.GetString("JsonEndObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на null.
        /// </summary>
        internal static string JsonNull {
            get {
                return ResourceManager.GetString("JsonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JSON.
        /// </summary>
        internal static string JsonPageTitle {
            get {
                return ResourceManager.GetString("JsonPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;property&quot; :.
        /// </summary>
        internal static string JsonProperty {
            get {
                return ResourceManager.GetString("JsonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [.
        /// </summary>
        internal static string JsonStartArray {
            get {
                return ResourceManager.GetString("JsonStartArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {.
        /// </summary>
        internal static string JsonStartObject {
            get {
                return ResourceManager.GetString("JsonStartObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на undefined.
        /// </summary>
        internal static string JsonUndefined {
            get {
                return ResourceManager.GetString("JsonUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗНАЧЕНИЕ.
        /// </summary>
        internal static string JsonValue {
            get {
                return ResourceManager.GetString("JsonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последнее время доступа.
        /// </summary>
        internal static string LastAccessTime {
            get {
                return ResourceManager.GetString("LastAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последнее время записи.
        /// </summary>
        internal static string LastWriteTime {
            get {
                return ResourceManager.GetString("LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длинное.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенести.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенести каталог.
        /// </summary>
        internal static string MoveDirectory {
            get {
                return ResourceManager.GetString("MoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передвинуть файл.
        /// </summary>
        internal static string MoveFile {
            get {
                return ResourceManager.GetString("MoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на загружено за мс: .
        /// </summary>
        internal static string NotifyFooter {
            get {
                return ResourceManager.GetString("NotifyFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обьектов внутри.
        /// </summary>
        internal static string ObjectCount {
            get {
                return ResourceManager.GetString("ObjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родитель.
        /// </summary>
        internal static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корень.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите номер позиции относительно текущей для перехода.
        /// </summary>
        internal static string Seek {
            get {
                return ResourceManager.GetString("Seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти.
        /// </summary>
        internal static string SeekTitle {
            get {
                return ResourceManager.GetString("SeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите новый размер файла в байтах.
        /// </summary>
        internal static string SetLength {
            get {
                return ResourceManager.GetString("SetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить размер.
        /// </summary>
        internal static string SetLengthTitle {
            get {
                return ResourceManager.GetString("SetLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Короткий.
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логаут.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Облако.
        /// </summary>
        internal static string SlotAPI {
            get {
                return ResourceManager.GetString("SlotAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Потокер.
        /// </summary>
        internal static string Streamer {
            get {
                return ResourceManager.GetString("Streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Потокер.
        /// </summary>
        internal static string StreamerTitle {
            get {
                return ResourceManager.GetString("StreamerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовый документ.
        /// </summary>
        internal static string TextPageTitle {
            get {
                return ResourceManager.GetString("TextPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На API-&gt;.
        /// </summary>
        internal static string ToAPI {
            get {
                return ResourceManager.GetString("ToAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий свободный объем.
        /// </summary>
        internal static string TotalFree {
            get {
                return ResourceManager.GetString("TotalFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид диска.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео.
        /// </summary>
        internal static string VideoTitle {
            get {
                return ResourceManager.GetString("VideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя тома.
        /// </summary>
        internal static string VolumeLabel {
            get {
                return ResourceManager.GetString("VolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите через пробел байты,на конце пробела быть не должно.
        /// </summary>
        internal static string WriteBytes {
            get {
                return ResourceManager.GetString("WriteBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить байты.
        /// </summary>
        internal static string WriteBytesTitle {
            get {
                return ResourceManager.GetString("WriteBytesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая строка.
        /// </summary>
        internal static string WriteLine {
            get {
                return ResourceManager.GetString("WriteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АТРИБУТ.
        /// </summary>
        internal static string XmlAttribute {
            get {
                return ResourceManager.GetString("XmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя и значение (через =).
        /// </summary>
        internal static string XmlAttributePattern {
            get {
                return ResourceManager.GetString("XmlAttributePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОММЕНТ.
        /// </summary>
        internal static string XmlComment {
            get {
                return ResourceManager.GetString("XmlComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОНЕЦ ДОКУМЕНТА.
        /// </summary>
        internal static string XmlEndDocument {
            get {
                return ResourceManager.GetString("XmlEndDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОНЕЦ ЭЛЕМЕНТА.
        /// </summary>
        internal static string XmlEndElement {
            get {
                return ResourceManager.GetString("XmlEndElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XML.
        /// </summary>
        internal static string XmlPageTitle {
            get {
                return ResourceManager.GetString("XmlPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СТАРТ ДОКУМЕНТА.
        /// </summary>
        internal static string XmlStartDocument {
            get {
                return ResourceManager.GetString("XmlStartDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СТАРТ ЭЛЕМЕНТА.
        /// </summary>
        internal static string XmlStartElement {
            get {
                return ResourceManager.GetString("XmlStartElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗНАЧЕНИЕ.
        /// </summary>
        internal static string XmlValue {
            get {
                return ResourceManager.GetString("XmlValue", resourceCulture);
            }
        }
    }
}
